### PR TITLE
Pr

### PR DESCRIPTION
**Pull request by sergueik**
Added few tests, disabled currently failing ones which deserve debugging.  Downgraded to  junit 5.3.2 and added WebDriverMaager to take care of chromedriver and xvfb  display setup for travis to exercise the tests.  Compressed the Javascrit snipets called fromm Java to simlify  future action logging in debug mode

### CODE REVIEW

**Comment by sergueik** [comment]
Hello Sushil Kumar Gupta,

Hope you had great holidays and New Year.

I was a litle busy with you know, my main place of work. I think we need to confinue forucing on pushing changes demonstrating additional functionaliy of the Shadow root DOM Selenium proxy project.

Thanks,

Serguei Kouzmine



     On Tuesday, December 31, 2019, 4:25:50 AM GMT+1, Sushil Kumar Gupta <notifications@github.com> wrote:  
 
 
Merged #11 into master.

**Comment by sergueik** [comment]
Hello Sushil Kumar 
i am preparing the new PR with a first tiny querySelector.js fix and a few refactoring to improve the project.. likely tonight ro tomorrow

Have a good day


Thanks

Serguei Kouzmine
     On Tuesday, December 31, 2019, 4:25:50 AM GMT+1, Sushil Kumar Gupta <notifications@github.com> wrote:  
 
 
Merged #11 into master.

**Comment by sukgu** [comment]
Hi,

Sure, please go ahead 👍

**Comment by sergueik** [comment]
I added more tests using shadow root to explore the chrome://downloads location. The code is currently broken in TRAVIS, because the chrome settings which worked in the desktop environment are not quite right. I still invite to take a look at my fork. After i download pdf file *which is a frequent topic among those QA forums - i find it in downloads etc. Have not tried multiple downloads during one single test about to ,soon

Thanks 
have a good rest of the day

Serguei Kouzmine     On Friday, January 24, 2020, 07:09:01 AM GMT+1, Sushil Kumar Gupta <notifications@github.com> wrote:  
 
 Hi,

Sure, please go ahead 👍

**Comment by sukgu** [comment]
It looks great, btw the getText() on line 153 should be working as expected. I will check it ASAP. 👍

**Pull request merged**
