### PR TITLE
Remove Thread.sleep(1000)

### PR DESCRIPTION
**Pull request by kelunik**
This makes everything quite slow.

### CODE REVIEW

**Comment by sukgu** [comment]
This is a failsafe approach as it belongs to waitForPageLoaded method. We need a better approach where we have ajax that takes time to load even after the page load completes. Until we have a better approach to do this I think its better to let it be here for now.

**Comment by kelunik** [comment]
For these cases, implicit wait can be configured, no? This makes a sequence of multiple findElements assertions on the same page very slow, because each assert goes through the sleep again.

I'm also fine with having a config option for this, but we don't need this wait at all, as we have a wrapping wait condition that solves this without any hard value.

**Comment by sukgu** [comment]
I tried this with a heavily loaded shadow DOM page and it seems to work fine with Implicit wait. I think we can remove this. I will try with few more websites to check the impact. For now lets merge this PR 👍

**Comment by kelunik** [comment]
Thanks!

**Comment by kelunik** [comment]
@sukgu Could you also tag a new release with the fix, please?

**Comment by sukgu** [comment]
@kelunik released 0.1.4.1 with changes.

**Pull request merged**
